# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 399)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(148, 148, 148);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pbn_revers = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_revers.setGeometry(QtCore.QRect(0, 350, 75, 50))
        self.pbn_revers.setObjectName("pbn_revers")
        self.pbn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_1.setGeometry(QtCore.QRect(0, 300, 75, 50))
        self.pbn_1.setObjectName("pbn_1")
        self.pbn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_4.setGeometry(QtCore.QRect(0, 250, 75, 50))
        self.pbn_4.setObjectName("pbn_4")
        self.pbn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_7.setGeometry(QtCore.QRect(0, 200, 75, 50))
        self.pbn_7.setObjectName("pbn_7")
        self.pbn_M_add = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_M_add.setGeometry(QtCore.QRect(0, 100, 75, 50))
        self.pbn_M_add.setObjectName("pbn_M_add")
        self.pbn_C = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_C.setGeometry(QtCore.QRect(0, 150, 75, 50))
        self.pbn_C.setObjectName("pbn_C")
        self.pbn_tochka = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_tochka.setGeometry(QtCore.QRect(70, 350, 75, 50))
        self.pbn_tochka.setObjectName("pbn_tochka")
        self.pbn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_2.setGeometry(QtCore.QRect(70, 300, 75, 50))
        self.pbn_2.setObjectName("pbn_2")
        self.pbn_MC = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_MC.setGeometry(QtCore.QRect(70, 100, 75, 50))
        self.pbn_MC.setObjectName("pbn_MC")
        self.pbn_CE = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_CE.setGeometry(QtCore.QRect(70, 150, 75, 50))
        self.pbn_CE.setObjectName("pbn_CE")
        self.pbn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_8.setGeometry(QtCore.QRect(70, 200, 75, 50))
        self.pbn_8.setObjectName("pbn_8")
        self.pbn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_5.setGeometry(QtCore.QRect(70, 250, 75, 50))
        self.pbn_5.setObjectName("pbn_5")
        self.pbn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_3.setGeometry(QtCore.QRect(140, 300, 75, 50))
        self.pbn_3.setObjectName("pbn_3")
        self.pbn_M_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_M_minus.setGeometry(QtCore.QRect(140, 100, 75, 50))
        self.pbn_M_minus.setObjectName("pbn_M_minus")
        self.pbn_procent = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_procent.setGeometry(QtCore.QRect(140, 150, 75, 50))
        self.pbn_procent.setObjectName("pbn_procent")
        self.pbn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_9.setGeometry(QtCore.QRect(140, 200, 75, 50))
        self.pbn_9.setObjectName("pbn_9")
        self.pbn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_6.setGeometry(QtCore.QRect(140, 250, 75, 50))
        self.pbn_6.setObjectName("pbn_6")
        self.pbn_result = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_result.setGeometry(QtCore.QRect(220, 350, 75, 50))
        self.pbn_result.setObjectName("pbn_result")
        self.pbn_add = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_add.setGeometry(QtCore.QRect(220, 300, 75, 50))
        self.pbn_add.setObjectName("pbn_add")
        self.pbn_del = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_del.setGeometry(QtCore.QRect(220, 150, 75, 50))
        self.pbn_del.setObjectName("pbn_del")
        self.pbn_backspace = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_backspace.setGeometry(QtCore.QRect(220, 100, 75, 50))
        self.pbn_backspace.setObjectName("pbn_backspace")
        self.pbn_multi = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_multi.setGeometry(QtCore.QRect(220, 200, 75, 50))
        self.pbn_multi.setObjectName("pbn_multi")
        self.pbn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_minus.setGeometry(QtCore.QRect(220, 250, 75, 50))
        self.pbn_minus.setObjectName("pbn_minus")
        self.pbn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_0.setGeometry(QtCore.QRect(140, 350, 75, 50))
        self.pbn_0.setObjectName("pbn_0")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pbn_revers.setText(_translate("MainWindow", "-/+"))
        self.pbn_1.setText(_translate("MainWindow", "1"))
        self.pbn_4.setText(_translate("MainWindow", "4"))
        self.pbn_7.setText(_translate("MainWindow", "7"))
        self.pbn_M_add.setText(_translate("MainWindow", "M+"))
        self.pbn_C.setText(_translate("MainWindow", "C"))
        self.pbn_tochka.setText(_translate("MainWindow", "."))
        self.pbn_2.setText(_translate("MainWindow", "2"))
        self.pbn_MC.setText(_translate("MainWindow", "MC"))
        self.pbn_CE.setText(_translate("MainWindow", "CE"))
        self.pbn_8.setText(_translate("MainWindow", "8"))
        self.pbn_5.setText(_translate("MainWindow", "5"))
        self.pbn_3.setText(_translate("MainWindow", "3"))
        self.pbn_M_minus.setText(_translate("MainWindow", "M-"))
        self.pbn_procent.setText(_translate("MainWindow", "%"))
        self.pbn_9.setText(_translate("MainWindow", "9"))
        self.pbn_6.setText(_translate("MainWindow", "6"))
        self.pbn_result.setText(_translate("MainWindow", "="))
        self.pbn_add.setText(_translate("MainWindow", "+"))
        self.pbn_del.setText(_translate("MainWindow", "/"))
        self.pbn_backspace.setText(_translate("MainWindow", "<="))
        self.pbn_multi.setText(_translate("MainWindow", "*"))
        self.pbn_minus.setText(_translate("MainWindow", "-"))
        self.pbn_0.setText(_translate("MainWindow", "0"))

    def add_function(self):
        self.pbn_0.clicked.connect(lambda:self.write_number(self.pbn_0.text()))
        self.pbn_1.clicked.connect(lambda: self.write_number(self.pbn_1.text()))
        self.pbn_2.clicked.connect(lambda: self.write_number(self.pbn_2.text()))
        self.pbn_3.clicked.connect(lambda: self.write_number(self.pbn_3.text()))
        self.pbn_4.clicked.connect(lambda: self.write_number(self.pbn_4.text()))
        self.pbn_5.clicked.connect(lambda: self.write_number(self.pbn_5.text()))
        self.pbn_6.clicked.connect(lambda: self.write_number(self.pbn_6.text()))
        self.pbn_7.clicked.connect(lambda: self.write_number(self.pbn_7.text()))
        self.pbn_8.clicked.connect(lambda: self.write_number(self.pbn_8.text()))
        self.pbn_9.clicked.connect(lambda: self.write_number(self.pbn_9.text()))
        self.pbn_add.clicked.connect(lambda: self.write_number(self.pbn_add.text()))
        self.pbn_minus.clicked.connect(lambda: self.write_number(self.pbn_minus.text()))
        self.pbn_multi.clicked.connect(lambda: self.write_number(self.pbn_multi.text()))
        self.pbn_del.clicked.connect(lambda: self.write_number(self.pbn_del.text()))
        self.pbn_tochka.clicked.connect(lambda: self.write_number(self.pbn_tochka.text()))
        self.pbn_procent.clicked.connect(lambda: self.write_number(self.pbn_procent.text()))
        self.pbn_C.clicked.connect(self.C)
        self.pbn_CE.clicked.connect(self.C)
        self.pbn_backspace.clicked.connect(self.Backspace)
        # self.pbn_revers.clicked.connect(self.revers)


        self.pbn_result.clicked.connect(self.result)
    def write_number(self, number):
        if self.label.text() == '0':
            self.label.setText(number)
        else:
            self.label.setText(self.label.text()+number)


    def Backspace(self):
        if self.label.text() != '0':
            res = self.label.text()
            res = res[:-1]

            self.label.setText(res)

    # def revers(self):
    #
    #     res = abs(self.label.text())
    #
    #     print(res)
    #     # self.label.setText(res)

    def result(self):
        res = eval(self.label.text())
        self.label.setText(str(res))

    def C(self):
        if self.label.text() != '0':
            self.label.setText('0')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
